### ISSUE TITLE
formatting vs formatting_sync

### ISSUE THREAD

**Issue by alex-popov-tech** [phelipetls/dotfiles#1]
Hey! I came from https://phelipetls.github.io/posts/configuring-eslint-to-work-with-neovim-lsp/
First things first, THANK YOU for that post, i was struggling with linting/formatting thorugh lsp...

and to the question itself - im usually hooking formatting on buffer write, and i often write and immediately continue writing...so im using formatting_sync usually, and it works for lua, but not for ts/js...do you know why? is it related to daemonizing eslint?

**Comment by phelipetls** [comment]
Hey Alexander, sorry I didn't check my email much these days.

I also had that problem. Just now I submitted a PR to neovim with what worked for me.

For now I just put

function vim.lsp.buf.formatting_sync(options, timeout_ms)
  local params = vim.lsp.util.make_formatting_params(options)
  local results = vim.lsp.buf_request_sync(0, "textDocument/formatting", params, timeout_ms)
  if not results or vim.tbl_isempty(results) then
    return
  end
  for _, result in ipairs(results) do
    if result and not vim.tbl_isempty(result) then
      vim.lsp.util.apply_text_edits(result.result)
    end
  end
end

in my init.vim.

I think it doesn't work because we are using two servers and only the changes for formatting from one server is being applied (tsserver I guess). But I'm not 100% sure.

I'm glad I helped!


________________________________
De: Alexander Popov <notifications@github.com>
Enviado: quarta-feira, 30 de dezembro de 2020 20:26
Para: phelipetls/dotfiles <dotfiles@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [phelipetls/dotfiles] formatting vs formatting_sync (#1)


Hey! I came from https://phelipetls.github.io/posts/configuring-eslint-to-work-with-neovim-lsp/
First things first, THANK YOU for that post, i was struggling with linting/formatting thorugh lsp...

and to the question itself - im usually hooking formatting on buffer write, and i often write and immediately continue writing...so im using formatting_sync usually, and it works for lua, but not for ts/js...do you know why? is it related to daemonizing eslint?

**Comment by phelipetls** [comment]
Just forget what I said. I did something wrong that worked for a very specific use case. The formatters would conflict with each other so it seems you need to choose only one.

What I did just now was to disable formatting for tsserver and enable formatting for efm-langserver (not satisfied with the way I did it, since it disables formatting for the entire client, hence why I need to re-enable for efm, but it works for now). See #54f2233.
